In [52]:
import numpy as np
import pandas as pd

In [53]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [54]:
data_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
Reason_1                     700 non-null int64
Reason_2                     700 non-null int64
Reason_3                     700 non-null int64
Reason_4                     700 non-null int64
Month value                  700 non-null int64
Day_of_the_week              700 non-null int64
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pet                          700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(14)
memory usage: 82.1 KB


In [55]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day_of_the_week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [56]:
#Categories of dependent variable (y): moderately absent is < median absent hours, excessively absent is > median absent hours
#Moderately (<3) = 0
#Excessively (>3) = 1
#These are the targets
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [57]:
#Targets of dependent variable
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [58]:
data_preprocessed['Excessive Absenteeism'] = targets

In [59]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day_of_the_week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [60]:
#Check the balance of the data for the dependent variable
targets.sum()/targets.shape[0]

0.45571428571428574

In [61]:
#Checkpoint copy of database
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 
                                            'Day_of_the_week', 
                                            'Distance to Work', 
                                            'Daily Work Load Average'], axis=1)  
#The exclusion of Day_of_the_week, Distance to Work and Daily Work Load Average was becasue they contributed little to the model
#when they were included.
#Kernel - Restart and Run All to re-run the entire model again

In [62]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [63]:
#Select independent variables/inputs for regression
unscaled_inputs = data_with_targets.iloc[ : , : -1]  #All columns except the last

In [64]:
#Standardise the data
from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler() #Used to subtract the mean and divide by the standard deviation variablewise

#Whenever you get new data you will know that the standardisation info is contained in the absenteeism_scaler. So you can
#standardise the new data in the same way

#But this scaler scales ALL columns, when we don't want the dummy variables (Reason 1,2,3,4, Education) to be scaled

In [65]:
#Create a custom scaler so that the dummy variables (Reason 1,2,3,4) aren't standardised too. 
#It allows you to choose the variables that you'd like to scale.
from sklearn.base import BaseEstimator, TransformerMixin
class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy = True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self_var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis = 1)[init_col_order]

In [66]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [67]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [68]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit] #excludes columns in the 
#columns_to_omit list

In [69]:
absenteeism_scaler = CustomScaler(columns_to_scale) #This is the scaling mechanism

In [70]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\WendyW\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['Month value', 'Transportation Expense', 'Age', 'Body Mass Index', 'Children', 'Pet'],
       copy=None, with_mean=None, with_std=None)

In [71]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs) #Transforms the unscaled inputs using information contained in
#absenteeism_scaler (i.e. subtract the mean and divide by the standard deviation variablewise)

C:\Users\WendyW\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:20: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.


__(NOTE FOR FUTURE USE ON NEW DATA)__

In [21]:
#When we get new data, apply the absenteeism_scaler to transform the data
#new_data_raw = pd.read_csv('new_data.csv')
#new_data_scaled = absenteeism_scaler.transform(new_data_raw)

In [72]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
5           0         0         0         1     0.182726   
6           0         0         0         1     0.182726   
7           0         0         0         1     0.182726   
8           0         0         1         0     0.182726   
9           0         0         0         1     0.182726   
10          1         0         0         0     0.182726   
11          1         0         0         0     0.182726   
12          1         0         0         0     0.182726   
13          1         0         0         0     0.182726   
14          0         0         0         1     0.182726   
15          1         0         0         0     0.182726   
16          0         0         0         1     0.182726   
17          0         0         1         0     0.182726   
18          1         0         0         0     0.182726   
19          0         0         0         1     0.468236   
20          1         0         0         0     0.468236   
21          1         0         0         0     0.468236   
22          1         0         0         0     0.468236   
23          0         0         0         1     0.468236   
24          0         0         1         0     0.468236   
25          0         0         0         1     0.468236   
26          0         0         0         1     0.468236   
27          0         0         0         1     0.468236   
28          0         0         1         0     0.468236   
29          0         0         0         1     0.468236   
..        ...       ...       ...       ...          ...   
670         0         0         0         1    -0.673803   
671         0         0         1         0    -0.673803   
672         1         0         0         0    -0.673803   
673         0         0         0         1    -0.673803   
674         0         0         0         1    -0.388293   
675         0         0         1         0    -0.388293   
676         0         0         0         1    -0.388293   
677         1         0         0         0    -0.388293   
678         0         0         0         1    -0.388293   
679         1         0         0         0    -0.388293   
680         0         0         0         1    -0.388293   
681         1         0         0         0    -0.388293   
682         0         0         1         0    -0.388293   
683         0         0         0         1    -0.388293   
684         0         0         0         1    -0.388293   
685         0         0         0         1    -0.388293   
686         1         0         0         0    -0.388293   
687         0         0         0         1    -0.388293   
688         0         0         0         0    -0.388293   
689         0         0         0         1    -0.388293   
690         0         0         0         0    -0.388293   
691         0         1         0         0    -0.388293   
692         1         0         0         0    -0.388293   
693         1         0         0         0    -0.388293   
694         0         0         0         1    -0.388293   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1

In [73]:
scaled_inputs.shape

(700, 11)

In [74]:
#Train and test datasets and shuffle dataset
from sklearn.model_selection import train_test_split

In [134]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)
#Produces 4 data arrays:
#1. Training dataset with inputs (x_train)
#2. Test dataset with inputs (x_test)
#3. Training dataset with targets (y_train)
#4. Test dataset with targets(y_test)

#80%/20% split
#shuffle is true by default. random_state makes the model shuffle the observations in the same random way

C:\Users\WendyW\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [76]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [117]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


__Logistic regression__

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [79]:
reg = LogisticRegression()

In [80]:
reg.fit(x_train, y_train)

C:\Users\WendyW\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [81]:
#Accuracy score
reg.score(x_train, y_train) #model has accuracy of 80%

0.775

In [82]:
#Manually identify accuracy score

#Model outputs
model_outputs = reg.predict(x_train) 
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [83]:
#Actual outputs
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [84]:
#Compare model output with acrual outputs (y_train)
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [85]:
np.sum((model_outputs == y_train)) #Sums the number of true entries

434

In [86]:
model_outputs.shape[0]

560

In [87]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.775

In [88]:
#Finding the intercept (C) and coefficients (A) of the logistic regression model
#log(odds) = C + A1X1 + A2X2 + ...+ AzXz
reg.intercept_

array([-1.46547112])

In [89]:
 reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.15493732,
         0.59979822, -0.17245127,  0.27568526, -0.23452541,  0.34249662,
        -0.2775137 ]])

In [90]:
#The coefficient names are:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [91]:
feature_name = unscaled_inputs.columns.values

In [92]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)

summary_table['Coefficients'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficients
0                 Reason_1      2.627499
1                 Reason_2      0.863386
2                 Reason_3      2.960507
3                 Reason_4      0.663907
4              Month value      0.154937
5   Transportation Expense      0.599798
6                      Age     -0.172451
7          Body Mass Index      0.275685
8                Education     -0.234525
9                 Children      0.342497
10                     Pet     -0.277514

In [93]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficients
0                Intercept     -1.465471
1                 Reason_1      2.627499
2                 Reason_2      0.863386
3                 Reason_3      2.960507
4                 Reason_4      0.663907
5              Month value      0.154937
6   Transportation Expense      0.599798
7                      Age     -0.172451
8          Body Mass Index      0.275685
9                Education     -0.234525
10                Children      0.342497
11                     Pet     -0.277514

In [94]:
#Coefficients are in log odds. Find exponential of the coefficients
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)
summary_table

Feature name  Coefficients  Odds_ratio
0                Intercept     -1.465471    0.230969
1                 Reason_1      2.627499   13.839121
2                 Reason_2      0.863386    2.371177
3                 Reason_3      2.960507   19.307751
4                 Reason_4      0.663907    1.942367
5              Month value      0.154937    1.167585
6   Transportation Expense      0.599798    1.821751
7                      Age     -0.172451    0.841599
8          Body Mass Index      0.275685    1.317433
9                Education     -0.234525    0.790946
10                Children      0.342497    1.408460
11                     Pet     -0.277514    0.757665

In [95]:
summary_table.sort_values('Odds_ratio', ascending = False)
#When coefficient is close to 0, not important
#When odds ratio is close to 1, not important

#Variables that contribute little to the model can be removed above and have the model re-run

Feature name  Coefficients  Odds_ratio
3                 Reason_3      2.960507   19.307751
1                 Reason_1      2.627499   13.839121
2                 Reason_2      0.863386    2.371177
4                 Reason_4      0.663907    1.942367
6   Transportation Expense      0.599798    1.821751
10                Children      0.342497    1.408460
8          Body Mass Index      0.275685    1.317433
5              Month value      0.154937    1.167585
7                      Age     -0.172451    0.841599
9                Education     -0.234525    0.790946
11                     Pet     -0.277514    0.757665
0                Intercept     -1.465471    0.230969

__Test the model__

In [135]:
reg.score(x_test, y_test)
#In 75% of the cases, the model will predict the absenteeism level corretly.

0.75

In [136]:
#When new data is acquired, clean the data as was done above and run the code in here
predicted_absenteeism = reg.predict(x_test)
predicted_absenteeism

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0])

In [137]:
x_test_copy1 = x_test.copy()
x_test_copy1.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  \
535         0         0         0         1     1.324766   
281         0         0         0         1     0.753746   
324         0         0         0         1     1.324766   
645         0         0         0         1    -0.959313   
10          1         0         0         0     0.182726   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
535               -0.654143  0.248310         1.002633          0 -0.919030   
281                1.036026  0.562059        -0.408580          0 -0.019280   
324                0.190942  1.032682         2.649049          0 -0.019280   
645               -0.654143  0.248310         1.002633          0 -0.919030   
10                 0.568211 -0.065439        -0.878984          0  2.679969   

          Pet  
535 -0.589690  
281  0.268487  
324 -0.589690  
645 -0.589690  
10  -0.589690

In [139]:
# a function which outputs 0 or 1 based on our model
predictions = reg.predict(x_test_copy1)
predictions

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0])

In [141]:
#Return the probability estimates for all possible outputs (in this case, 0 or 1)
predicted_proba = reg.predict_proba(x_test_copy1)
predicted_proba

#Probability estimates indicate, per record, the probability of resulting in “0 (<3 hours)” or “1 (>3 hours)”. 
#If probability is <0.5, then “0 (<3 hours)” result, if >0.5 then a “1 (>3 hours)”.

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.

In [142]:
#Then add the predctions and probabilities to the x_test dataset. HERE IT WAS ADDED TO THE STANDARDISED DATASET, 
#RATHER ADD TO THE RAW DATA
x_test_copy1['Prediction'] = predictions 


In [144]:
x_test_copy1['Probabilities'] = predicted_proba[:, 1] #Adds the probability of "1" (>3 hours absent) to the data

In [145]:
x_test_copy1.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  \
535         0         0         0         1     1.324766   
281         0         0         0         1     0.753746   
324         0         0         0         1     1.324766   
645         0         0         0         1    -0.959313   
10          1         0         0         0     0.182726   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
535               -0.654143  0.248310         1.002633          0 -0.919030   
281                1.036026  0.562059        -0.408580          0 -0.019280   
324                0.190942  1.032682         2.649049          0 -0.019280   
645               -0.654143  0.248310         1.002633          0 -0.919030   
10                 0.568211 -0.065439        -0.878984          0  2.679969   

          Pet  Prediction  Probabilities  
535 -0.589690           0       0.287780  
281  0.268487           0       0.412400  
324 -0.589690           1       0.556626  
645 -0.589690           0       0.220960  
10  -0.589690           1       0.915417

__Save the model__

In [98]:
#Equivalent to saving the reg function into a file
#Pickle is a pyhton modeul used to convert a python object into a character stream (strings). Note: pick is not secure, only
#unpickle data from atrusted source
#Must save the absenteeism scaler! Needed to pre-process any new data
import pickle

In [99]:
with open ('model', 'wb') as file:
    pickle.dump(reg, file)

In [100]:
with open ('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler , file)

__Load the model to run on new data__

In [ ]:
#Clumsy approach - execute the entire code above again
#Clever approach - create a module, code provided in Lecture 68
#Saved absenteeism_module.py

#Test the model and new data in new jupyter file "Absenteeism Exercise - Integration.ipynb" IT DOESN'T WORK!!